import classes from "../styles/index.module.css";
import TypeWritter from "@/components/home/TypeWritter";
import ParticlesBackground from "@/components/layout/ParticlesBackground";
import Head from "next/head";
import Footer from "@/components/layout/Footer";

export default function Home() {
  return (
    <>
      <ParticlesBackground />
      <Head>
        <title>Maziuk's Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TypeWritter />
      <Footer class="footer" />
    </>
  );
}
